### ISSUE TITLE
Nearby Surau/Masjid locator Pinned not accurate.

### ISSUE THREAD

**Issue by aniqaqill** [khrnchn/sedekah-je#297]
**Describe the bug**
Masjid/Surau terdekat yang sebenar tidak terpapar di muka halaman . 
**To Reproduce**
1. Go to Home Page
2. See on the pinned nearest qr code

**Expected behavior**
A accurate nearest Masjid/Surau appear in the home page

**Screenshots**
![Screenshot_20241230-102404.png](https://github.com/user-attachments/assets/92191219-7ec8-4d05-9f0c-f42844f505fe)

![Screenshot_20241230-102349.png](https://github.com/user-attachments/assets/2b0ffda9-43f1-46cb-b281-ec7ae2869af4)

![Screenshot_20241230-102241.png](https://github.com/user-attachments/assets/3b284f6f-2f8f-49a2-b66c-eb803a346570)

**Additional context**

**Comment by khrnchn** [comment]
yes, sekarang semua institutions data hardcoded dalam `institutions.ts`. coords pun sama, banyak lagi yang takde coords. kalau nearest mosque kau ada dalam sedekahje tapi not being pinned, thats due to missing coords.

ni plan aku for january:

1. seed existing institutions data into db
2. create dashboard for admin(s) to manage institutions (fetch missing coords and save, add social links etc)
3. create ui for public users to contribute qr (so we can ditch google form or other channels like whatsapp twitter etc)

lepas siap semua ni boleh focus on collecting more masjid/surau qrs

**Comment by aniqaqill** [comment]
alright will add few coords manually then , aku try add a few dulu

**Comment by khrnchn** [comment]
#295
