### ISSUE TITLE
WTA : How do I can contribute for adding data 

### ISSUE THREAD

**Issue by luqmanafif96** [khrnchn/sedekah-je#34]
Context: I have some data I want to add at Sedekahjer )) but following using qrtool unable to extract
![surau_hj_omar](https://github.com/user-attachments/assets/02091800-d781-45e0-819b-11f1f76c3c19)

**Comment by khrnchn** [comment]
either

1. fork the repo and add new entry into `institutions.ts`, (but still need qrContent to render)
2. [extract the qr content](https://qrcoderaptor.com/) 

same here, i think its due to this part of the qr:
![image](https://github.com/user-attachments/assets/e8c82fe2-12f9-4d07-a740-a7a2103eaaca)
![image](https://github.com/user-attachments/assets/e5b1827d-b4b7-4a96-ab8c-b3cacd939cd1)

**Comment by khrnchn** [comment]
ok dapat dari [sini](https://www.facebook.com/photo/?fbid=794956399325068&set=a.462191652601546&locale=ms_MY)

`00020201021126420014A000000615000101066033460210MD001301335204866153034585802MY5925Surau Hj Omar Jln Genting6002MY6273032517071030332970090364035730520170710363623000637960716170710184223100163040BE9`

**Comment by luqmanafif96** [comment]
thanks for help next time I will contribute more data ,
